db: /muse/UDF/private/analysis/musex.db
show_banner: true

extractors:
  hstprior:
    class: musex.prior.PriorExtractor
    settings: hstprior.yaml
  muse:
    class: musex.muse.MuseExtractor
    settings: muse.yaml
