db: /muse/UDF/private/analysis/musex.db
show_banner: true

hst_data_dir: '/muse/UDF/private/HST/XUDF'
muse_data_dir: '/muse/UDF/public/dataproducts'

datasources:
  hst:
    # HST data (images)
    version: '1.0'
    # filters: '/muse/UDF/private/HST/Filters'
    images:
      'F225W': '{hst_data_dir}/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f225w_v2.0_drz.fits'
      'F275W': '{hst_data_dir}/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f275w_v2.0_drz.fits'
      'F336W': '{hst_data_dir}/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f336w_v2.0_drz.fits'
      'F435W': '{hst_data_dir}/hlsp_xdf_hst_acswfc-30mas_hudf_f435w_v1_sci.fits'
      'F606W': '{hst_data_dir}/hlsp_xdf_hst_acswfc-30mas_hudf_f606w_v1_sci.fits'
      'F775W': '{hst_data_dir}/hlsp_xdf_hst_acswfc-30mas_hudf_f775w_v1_sci.fits'
      'F814W': '{hst_data_dir}/hlsp_xdf_hst_acswfc-30mas_hudf_f814w_v1_sci.fits'
      'F850LP': '{hst_data_dir}/hlsp_xdf_hst_acswfc-30mas_hudf_f850lp_v1_sci.fits'
      'F105W': '{hst_data_dir}/hlsp_xdf_hst_wfc3ir-60mas_hudf_f105w_v1_sci.fits'
      'F140W': '{hst_data_dir}/hlsp_xdf_hst_wfc3ir-60mas_hudf_f140w_v1_sci.fits'
      'F125W': '{hst_data_dir}/hlsp_xdf_hst_wfc3ir-60mas_hudf_f125w_v1_sci.fits'
      'F160W': '{hst_data_dir}/hlsp_xdf_hst_wfc3ir-60mas_hudf_f160w_v1_sci.fits'

  muse-udf-10:
    version: '1.0b1'
    datacube: '{muse_data_dir}/1.0b1/DATACUBE_UDF-10.fits'
    expcube: '{muse_data_dir}/1.0b1/EXPMAP_UDF-10.fits'
    expima: '{muse_data_dir}/1.0b1/EXPMAP-IMAGE_UDF-10.fits'
    images:
      white: '{muse_data_dir}/1.0b1/IMAGE_UDF-10.fits'

  muse-udf-mosaic:
    version: '1.0b1'
    datacube: '{muse_data_dir}/1.0b1/DATACUBE_UDF-MOSAIC.fits'
    expcube: '{muse_data_dir}/1.0b1/EXPMAP_UDF-MOSAIC.fits'
    expima: '{muse_data_dir}/1.0b1/EXPMAP-IMAGE_UDF-MOSAIC.fits'
    images:
      white: '{muse_data_dir}/1.0b1/IMAGE_UDF-MOSAIC.fits'

sourcefinders:
  hstprior:
    class: musex.detection.PriorCatalog
    version: '1.0'
    catalog: '/muse/UDF/private/HST/Catalogs/uvudf_rafelski_2015.fits'
    id_name: 'ID'
    segmap: '/muse/UDF/private/HST/SegMap/segmentation_map_rafelski_2015.fits'
  # muse:
  #   class: musex.detection.Origin
