# Paths for the working directory and database
workdir: '/muse/UDF/private/analysis/musex/work'
db: '{workdir}/../musex.db'

# Parameters for the MuseX object
show_banner: true
author: 'John Doe'
idmapping: muse_udf10

# Top-level keys are substituted in the file so they can be used to avoid
# repeating things like long file paths.
hst_data_dir: '/muse/UDF/private/HST'
muse_data_dir: '/muse/UDF/public/dataproducts'

# Define datasets, each image will be added to the sources as an extension
# with a name "[prefix]_[key]"
datasets:
  hst:
    # HST
    version: '1.0'
    prefix: HST
    # filters: '/muse/UDF/private/HST/Filters'
    images:
      F225W: '{hst_data_dir}/XUDF/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f225w_v2.0_drz.fits'
      F275W: '{hst_data_dir}/XUDF/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f275w_v2.0_drz.fits'
      F336W: '{hst_data_dir}/XUDF/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f336w_v2.0_drz.fits'
      F435W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f435w_v1_sci.fits'
      F606W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f606w_v1_sci.fits'
      F775W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f775w_v1_sci.fits'
      F814W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f814w_v1_sci.fits'
      F850LP: '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f850lp_v1_sci.fits'
      F105W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f105w_v1_sci.fits'
      F140W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f140w_v1_sci.fits'
      F125W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f125w_v1_sci.fits'
      F160W: '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f160w_v1_sci.fits'

# Define MUSE datasets. One MuseX object can handle only one MUSE dataset,
# chosen either with the default key or when instanciating the object.
muse_datasets:
  default: muse-udf-10

  muse-udf-10:
    version: '1.0b1'
    prefix: MUSE
    datacube: '{muse_data_dir}/1.0b1/DATACUBE_UDF-10.fits'
    # expcube: '{muse_data_dir}/1.0b1/EXPMAP_UDF-10.fits'
    expima: '{muse_data_dir}/1.0b1/EXPMAP-IMAGE_UDF-10.fits'
    white: '{muse_data_dir}/1.0b1/IMAGE_UDF-10.fits'

  muse-udf-mosaic:
    version: '1.0b1'
    prefix: MUSE
    datacube: '{muse_data_dir}/1.0b1/DATACUBE_UDF-MOSAIC.fits'
    # expcube: '{muse_data_dir}/1.0b1/EXPMAP_UDF-MOSAIC.fits'
    expima: '{muse_data_dir}/1.0b1/EXPMAP-IMAGE_UDF-MOSAIC.fits'
    white: '{muse_data_dir}/1.0b1/IMAGE_UDF-MOSAIC.fits'
    fieldmap: '{muse_data_dir}/1.0b1/FIELDMAP_UDF-MOSAIC.fits'

# Input catalogs. For each catalog, define the column name for the id, ra and
# dec. The extract block is used when putting a subset of the catalog as
# a source extension (named "[prefix]_CAT").
catalogs:

  rafelski:
    version: '1.0'
    catalog: '{hst_data_dir}/Catalogs/uvudf_rafelski_2015.fits'
    idname: ID
    raname: RA
    decname: DEC
    segmap: '{hst_data_dir}/SegMap/segmentation_map_rafelski_2015.fits'
    extract:
      prefix: HST
      columns: [ID, RA, DEC, MAG_F775W]
      select_in: HST_F775W
      redshifts:
        # Define redshift columns. The key is the name, and value can be just
        # the column name, or column names for Z, ZMIN and ZMAX.
        BPZ: [Z_BPZ, ZMIN_BPZ, ZMAX_BPZ]
        EASY: [Z_EAZY, ZMIN_EAZY, ZMAX_EAZY]
        SPECZ: SPECZ
        GRISMZ: GRISMZ
      mags:
        # Define magnitude columns. The key is the name, and value can be just
        # the column name, or column names for MAG and MAGERR.
        F225W: [MAG_F225W, MAGERR_F225W]
        F336W: [MAG_F336W, MAGERR_F336W]
        F435W: [MAG_F435W, MAGERR_F435W]
        F606W: [MAG_F606W, MAGERR_F606W]
        F775W: [MAG_F775W, MAGERR_F775W]
        F850LP: [MAG_F850LP, MAGERR_F850LP]
        F105W: [MAG_F105W, MAGERR_F105W]
        F125W: [MAG_F125W, MAGERR_F125W]
        F140W: [MAG_F140W, MAGERR_F140W]
        F160W: [MAG_F160W  MAGERR_F160W]

  photutils:
    version: '1.0'
    catalog: '{workdir}/../photutils-catalog.fits'
    idname: id
    raname: ra
    decname: dec
    segmap: '{workdir}/../photutils-segmap.fits'
    extract:
      prefix: PHU
      columns: [id, ra, dec, source_sum, area]
      select_in: HST_F775W
