workdir: '/muse/UDF/private/analysis/musex'
db: '{workdir}/musex.db'
show_banner: true

hst_data_dir: '/muse/UDF/private/HST'
muse_data_dir: '/muse/UDF/public/dataproducts'

datasets:
  hst:
    # HST data (images)
    version: '1.0'
    prefix: HST
    # filters: '/muse/UDF/private/HST/Filters'
    images:
      'F225W': '{hst_data_dir}/XUDF/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f225w_v2.0_drz.fits'
      'F275W': '{hst_data_dir}/XUDF/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f275w_v2.0_drz.fits'
      'F336W': '{hst_data_dir}/XUDF/hlsp_uvudf_hst_wfc3-uvis-30mas_udf-epoch3_f336w_v2.0_drz.fits'
      'F435W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f435w_v1_sci.fits'
      'F606W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f606w_v1_sci.fits'
      'F775W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f775w_v1_sci.fits'
      'F814W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f814w_v1_sci.fits'
      'F850LP': '{hst_data_dir}/XUDF/hlsp_xdf_hst_acswfc-30mas_hudf_f850lp_v1_sci.fits'
      'F105W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f105w_v1_sci.fits'
      'F140W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f140w_v1_sci.fits'
      'F125W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f125w_v1_sci.fits'
      'F160W': '{hst_data_dir}/XUDF/hlsp_xdf_hst_wfc3ir-60mas_hudf_f160w_v1_sci.fits'

muse_datasets:
  default: muse-udf-10

  muse-udf-10:
    version: '1.0b1'
    prefix: MUSE
    datacube: '{muse_data_dir}/1.0b1/DATACUBE_UDF-10.fits'
    expcube: '{muse_data_dir}/1.0b1/EXPMAP_UDF-10.fits'
    expima: '{muse_data_dir}/1.0b1/EXPMAP-IMAGE_UDF-10.fits'
    white: '{muse_data_dir}/1.0b1/IMAGE_UDF-10.fits'

  muse-udf-mosaic:
    version: '1.0b1'
    prefix: MUSE
    datacube: '{muse_data_dir}/1.0b1/DATACUBE_UDF-MOSAIC.fits'
    expcube: '{muse_data_dir}/1.0b1/EXPMAP_UDF-MOSAIC.fits'
    expima: '{muse_data_dir}/1.0b1/EXPMAP-IMAGE_UDF-MOSAIC.fits'
    white: '{muse_data_dir}/1.0b1/IMAGE_UDF-MOSAIC.fits'

catalogs:
  hstprior:
    prefix: HST
    class: musex.catalog.PriorCatalog
    version: '1.0'
    catalog: '{hst_data_dir}/Catalogs/uvudf_rafelski_2015.fits'
    colnames:
      idname: ID
      raname: RA
      decname: DEC
    segmap: '{hst_data_dir}/SegMap/segmentation_map_rafelski_2015.fits'
    masks:
      # path, name and size (arcseconds) of the extracted masks
      outpath: '{workdir}/hstprior'
      outname: 'mask-source-{{:05d}}.fits'
      convolve_fsf: 0.6
      size: [20, 20]
    extract:
      columns: [ID, RA, DEC, MAG_F775W]
      select_in: HST_F775W
      margin: 10
  # muse:
  #   class: musex.catalog.Origin

extraction:
  apertures: [0.4]
  additional_datasets: [hst]
