db: /muse/UDF/private/analysis/musex.db
show_banner: true

datasources:
  hst:
    settings: hst.yaml
  muse-udf-10:
    settings: muse-udf-10.yaml
  muse-udf-mosaic:
    settings: muse-udf-mosaic.yaml

# extractors:
#   hstprior:
#     class: musex.prior.PriorExtractor
#     settings: hstprior.yaml
#   muse:
#     class: musex.muse.MuseExtractor
#     settings: muse.yaml
