
db: '/muse/UDF/private/analysis/mouse.db'

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      format: "%(asctime)s [%(levelname)07s][%(threadName)s] %(name)s: %(message)s"
    colored:
      (): mpdaf.log.ColoredFormatter
      # format: "[%(process)s] %(asctime)s %(levelname)s - %(name)s: %(message)s"
      format: "[%(levelname)s] %(message)s"
    simple:
      format: "%(name)s: %(message)s"
  handlers:
    console:
      level: INFO
      class: logging.StreamHandler
      formatter: colored
    # file:
    #   level: DEBUG
    #   class: logging.FileHandler
    #   formatter: default
    #   filename: '{basedir}/datared/{version}/logs/%s.log'
    #   mode: w
    #   encoding: utf-8
  # loggers:
  #   'mydrs':
  #     handlers: [console]
  #     level: INFO
  #     propagate: True
  #   'mpdaf':
  #     handlers: [console]
  #     level: INFO
  #     propagate: True
  root:
    level: INFO
    handlers: [console]
